package com.abhi.webservice.testkit

/**
  * Created by ASrivastava on 10/27/17.
  */
object StatusCodes extends Enumeration {
   type StatusCodes = Value
   val Continue = Value(100)
   val SwitchingProtocols = Value(101)
   val Processing = Value(102)
   val OK = Value(200)
   val Created = Value(201)
   val Accepted = Value(202)
   val NonAuthoritativeInformation = Value(203)
   val NoContent = Value(204)
   val ResetContent = Value(205)
   val PartialContent = Value(206)
   val MultiStatus = Value(207)
   val AlreadyReported = Value(208)
   val IMUsed = Value(226)
   val MultipleChoices = Value(300)
   val MovedPermanently = Value(301)
   val Found = Value(302)
   val SeeOther = Value(303)
   val NotModified = Value(304)
   val UseProxy = Value(305)
   val TemporaryRedirect = Value(307)
   val PermanentRedirect = Value(308)
   val BadRequest = Value(400)
   val Unauthorized = Value(401)
   val PaymentRequired = Value(402)
   val Forbidden = Value(403)
   val NotFound = Value(404)
   val MethodNotAllowed = Value(405)
   val NotAcceptable = Value(406)
   val ProxyAuthenticationRequired = Value(407)
   val RequestTimeout = Value(408)
   val Conflict = Value(409)
   val Gone = Value(410)
   val LengthRequired = Value(411)
   val PreconditionFailed = Value(412)
   val RequestEntityTooLarge = Value(413)
   val RequestUriTooLong = Value(414)
   val UnsupportedMediaType = Value(415)
   val RequestedRangeNotSatisfiable = Value(416)
   val ExpectationFailed = Value(417)
   val EnhanceYourCalm = Value(420)
   val UnprocessableEntity = Value(422)
   val Locked = Value(423)
   val FailedDependency = Value(424)
   val UnorderedCollection = Value(425)
   val UpgradeRequired = Value(426)
   val PreconditionRequired = Value(428)
   val TooManyRequests = Value(429)
   val RequestHeaderFieldsTooLarge = Value(431)
   val RetryWith = Value(449)
   val BlockedByParentalControls = Value(450)
   val UnavailableForLegalReasons = Value(451)
   val InternalServerError = Value(500)
   val NotImplemented = Value(501)
   val BadGateway = Value(502)
   val ServiceUnavailable = Value(503)
   val GatewayTimeout = Value(504)
   val HTTPVersionNotSupported = Value(505)
   val VariantAlsoNegotiates = Value(506)
   val InsufficientStorage = Value(507)
   val LoopDetected = Value(508)
   val BandwidthLimitExceeded = Value(509)
   val NotExtended = Value(510)
   val NetworkAuthenticationRequired = Value(511)
   val NetworkReadTimeout = Value(598)
   val NetworkConnectTimeout = Value(599)
   def fromInt(code: Int) : Value = values.find(_.id == code) getOrElse {throw new RuntimeException("Unknown Code")}
}
